### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Benjoyo** [entrusc/Pi-RC-Switch#5]
I am using the library with Pi4J 1.0.1 and experienced some problems:
- first at least for my elro_800 compatible outlets the pulse length of 350 is too long, the protcoll says something around 280-320,  280 is fine for me.
-  the biggest problem is that the switchOn and switchOff methods work exactly one time respectively, then the program needs a restart. What fixes this is unprovisioning the transmitter pin after every switch and provisioning it again the next time. But that can't be the way, right?

I know that you use an older Pi4J version, but that shouldn't be an issue; and I need the new version.
Thanks.

**Comment by entrusc** [comment]
I'm not sure where your issues come from. My setup with some cheap RF-outlets works perfectly. The only problem I experience sometimes is that the transmitter range is a bit limited, but I guess that's due to the reduced voltage; the original remote control uses a 12V battery - and I guess that is for a reason.

But if the pulse length is too long for you, you are welcome to change the length and experiment with it. I think that each vendor might use a slightly different protocoll - but after all I'm not the original author of the code - I merely ported it to Java.

**Comment by chris0550** [comment]
> the biggest problem is that the switchOn and switchOff methods work exactly one time respectively

I have the same problem. I think the reason for this is that the pulseLength increases for some reason. I work with a pulseLength of 180 microseconds: 
 - Frist send -> ~183microseconds
 - Then all after that -> 400-420microseconds

My current workaround is to set a pulseLength of 90 instead of the correct 180.

(Pi4J version 1.2-SNAPSHOT)
